// Session mirroring: creates/updates GitHub issues and comments for each conversation.
import fs from "node:fs";
import path from "node:path";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/core";
import { AGENT_LABEL_PREFIX, DEFAULT_LABELS, SESSION_TITLE_PREFIX, extractLabelNames } from "./config.js";
import type { GitHubIssueClient } from "./github-client.js";
import { parseCandidates } from "./memory.js";
import { normalizeMessages, readTranscriptSnapshot } from "./transcript.js";
import type { ClawMemPluginConfig, MemoryCandidate, NormalizedMessage, SessionMirrorState, TranscriptSnapshot } from "./types.js";
import { fmtTranscript, localDate, localDateTime, sha256, subKey } from "./utils.js";
import { parseFlatYaml, stringifyFlatYaml } from "./yaml.js";

export class ConversationMirror {
  constructor(private readonly client: GitHubIssueClient, private readonly api: OpenClawPluginApi, private readonly config: ClawMemPluginConfig) {}

  shouldMirror(sessionId: string, messages: NormalizedMessage[]): boolean {
    if (sessionId.startsWith("slug-generator-")) return false;
    const first = messages.find((m) => m.role === "user")?.text ?? "";
    if (first.includes("generate a short 1-2 word filename slug") && first.includes("Reply with ONLY the slug")) return false;
    if (first.includes("Write the final issue summary and extract durable memory candidates from the conversation below.")) return false;
    return true;
  }

  async loadSnapshot(session: SessionMirrorState, fallback: unknown[]): Promise<TranscriptSnapshot> {
    const normalizedFallback = normalizeMessages(fallback);
    if (normalizedFallback.length > 0) {
      return { sessionId: session.sessionId, messages: normalizedFallback };
    }
    const filePath = await this.resolveTranscriptPath(session.sessionFile);
    if (filePath) {
      session.sessionFile = filePath;
      try {
        const t = await readTranscriptSnapshot(filePath);
        return { sessionId: t.sessionId ?? session.sessionId, messages: t.messages };
      } catch (error) {
        this.api.logger.warn(`clawmem: transcript read failed for ${filePath}: ${String(error)}`);
      }
    }
    return { sessionId: session.sessionId, messages: normalizedFallback };
  }

  async ensureIssue(session: SessionMirrorState, snapshot: TranscriptSnapshot): Promise<void> {
    if (session.issueNumber) {
      const existing = await this.lookupBoundIssue(session);
      if (existing && this.isBoundIssue(session, existing)) {
        session.issueTitle = existing.title?.trim() || session.issueTitle;
        return;
      }
      this.api.logger.warn(
        `clawmem: issue binding for ${session.sessionId} is stale or mismatched (${session.issueNumber}); recreating`,
      );
      this.resetIssueBinding(session);
    }
    // Use placeholder title; real title is generated by LLM once enough messages are available.
    const title = deriveInitialTitle(snapshot.messages, session.sessionId);
    const labels = this.buildLabels(session, snapshot, false);
    const body = this.renderBody(session, snapshot, "pending", false);
    await this.client.ensureLabels(labels);
    const issue = await this.client.createIssue({ title, body, labels });
    session.issueNumber = issue.number;
    session.issueTitle = issue.title ?? title;
    session.titleSource = "placeholder";
    session.lastSummaryHash = sha256(`${title}\n${body}\nopen`);
    session.createdAt = new Date().toISOString();
    session.updatedAt = session.createdAt;
  }

  async syncBody(session: SessionMirrorState, snapshot: TranscriptSnapshot, summary: string, closed: boolean, titleOverride?: string): Promise<void> {
    if (!session.issueNumber) return;
    // Prefer explicit override (LLM-generated title), then keep existing title, then fall back to session ID.
    const title = titleOverride?.trim() || session.issueTitle || `${SESSION_TITLE_PREFIX}${session.sessionId}`;
    const body = this.renderBody(session, snapshot, summary, closed);
    const hash = sha256(`${title}\n${body}\n${closed ? "closed" : "open"}`);
    if (hash === session.lastSummaryHash) return;
    await this.client.updateIssue(session.issueNumber, { title, body, ...(closed ? { state: "closed" as const } : {}) });
    session.issueTitle = title;
    if (titleOverride?.trim()) session.titleSource = "llm";
    session.lastSummaryHash = hash;
  }

  async syncLabels(session: SessionMirrorState, snapshot: TranscriptSnapshot, closed: boolean): Promise<void> {
    if (!session.issueNumber) return;
    const labels = this.buildLabels(session, snapshot, closed);
    await this.client.ensureLabels(labels);
    await this.client.syncManagedLabels(session.issueNumber, labels);
  }

  async appendComments(issueNumber: number, messages: NormalizedMessage[]): Promise<number> {
    let count = 0;
    for (const msg of messages) {
      try { await this.client.createComment(issueNumber, `role: ${msg.role}\n\n${msg.text.trim()}`); count++; }
      catch (error) { this.api.logger.warn(`clawmem: conversation comment failed: ${String(error)}`); break; }
    }
    return count;
  }

  async generateFinalArtifacts(
    session: SessionMirrorState,
    snapshot: TranscriptSnapshot,
  ): Promise<{ summary: string; title?: string; candidates: MemoryCandidate[] }> {
    if (snapshot.messages.length === 0) throw new Error("no conversation messages to finalize");
    const subagent = this.api.runtime.subagent;
    const sessionKey = subKey(session, "finalize");
    const message = [
      "Write the final issue summary and extract durable memory candidates from the conversation below.",
      'Return valid JSON only in the form {"summary":"...","title":"...","candidates":[{"title":"...","detail":"...","kind":"...","topics":["..."],"evidence":"..."}]}.',
      "The summary should be concise, factual, and written in 2-4 sentences.",
      "Do not include markdown, bullet points, or analysis.",
      "",
      "Title rules:",
      "- Under 50 characters, accurately describe the main topic or task.",
      "- Should let someone immediately know what the conversation is about.",
      "- Must be in the same language as the majority of the conversation content.",
      "- Good: precise, descriptive, specific. Bad: vague, overly creative, generic.",
      "",
      "Candidate rules:",
      "- Extract only durable facts, preferences, decisions, constraints, workflows, and ongoing context worth remembering later.",
      "- Each candidate must represent one durable fact. Split independent facts into separate candidates.",
      "- Do not extract temporary requests, tool chatter, startup boilerplate, or summaries about internal helper sessions.",
      "- Kind and topics are optional. Keep them short, reusable, and low-cardinality.",
      "- Evidence is optional. If present, keep it short and quote-free.",
      "- Prefer an empty candidates array when nothing durable was learned.",
      "",
      "<conversation>",
      fmtTranscript(snapshot.messages),
      "</conversation>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey,
        message,
        deliver: false,
        lane: "clawmem-finalize",
        idempotencyKey: sha256(`${session.sessionId}:${snapshot.messages.length}:finalize-v1`),
        extraSystemPrompt: "You finalize ClawMem conversations. Output JSON only with summary, title, and durable memory candidates.",
      });
      const wait = await subagent.waitForRun({
        runId: run.runId,
        timeoutMs: Math.max(this.config.summaryWaitTimeoutMs, this.config.memoryExtractWaitTimeoutMs),
      });
      if (wait.status === "timeout") throw new Error("finalize subagent timed out");
      if (wait.status === "error") throw new Error(wait.error || "finalize subagent failed");
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 50 })).messages);
      const text = [...msgs].reverse().find((entry) => entry.role === "assistant" && entry.text.trim())?.text;
      if (!text) throw new Error("finalize subagent returned no assistant text");
      return parseFinalArtifacts(text);
    } finally {
      subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {});
    }
  }

  private buildLabels(session: SessionMirrorState, _snapshot: TranscriptSnapshot, _closed: boolean): string[] {
    const labels = new Set([...DEFAULT_LABELS, "type:conversation", `session:${session.sessionId}`]);
    if (session.agentId) labels.add(`${AGENT_LABEL_PREFIX}${session.agentId}`);
    return [...labels].filter((l) => l.trim().length > 0);
  }

  private renderBody(session: SessionMirrorState, snapshot: TranscriptSnapshot, summary: string, _closed: boolean): string {
    const dates = this.resolveDates(session, snapshot.messages);
    return stringifyFlatYaml([
      ["type", "conversation"], ["session_id", session.sessionId], ["date", dates.date],
      ["start_at", dates.startAt], ["end_at", dates.endAt],
      ["summary", summary],
    ]);
  }

  private resolveDates(session: SessionMirrorState, messages: NormalizedMessage[]): { date: string; startAt: string; endAt: string } {
    const ts = messages.map((m) => m.timestamp).filter((v): v is string => Boolean(v?.trim()))
      .map((v) => new Date(v)).filter((d) => Number.isFinite(d.getTime()));
    const fallbackStart = session.createdAt ? new Date(session.createdAt) : new Date();
    const fallbackEnd = session.updatedAt ? new Date(session.updatedAt) : fallbackStart;
    const start = ts[0] ?? fallbackStart, end = ts.at(-1) ?? fallbackEnd;
    return { date: localDate(start), startAt: localDateTime(start), endAt: localDateTime(end) };
  }

  private async resolveTranscriptPath(filePath: string | undefined): Promise<string | null> {
    if (!filePath) return null;
    if (await fexists(filePath)) return filePath;
    try {
      const dir = path.dirname(filePath), prefix = `${path.basename(filePath)}.reset.`;
      const latest = (await fs.promises.readdir(dir, { withFileTypes: true }))
        .filter((e) => e.isFile() && e.name.startsWith(prefix)).map((e) => e.name).sort().at(-1);
      if (latest) {
        this.api.logger.info?.(`clawmem: using reset transcript ${path.join(dir, latest)} because ${filePath} is missing`);
        return path.join(dir, latest);
      }
    } catch { /* directory unreadable */ }
    return null;
  }

  private async lookupBoundIssue(session: SessionMirrorState): Promise<{ number: number; title?: string; labels?: Array<{ name?: string } | string> } | null> {
    if (!session.issueNumber) return null;
    try {
      return await this.client.getIssue(session.issueNumber);
    } catch (error) {
      if (isNotFoundError(error)) return null;
      throw error;
    }
  }

  private isBoundIssue(session: SessionMirrorState, issue: { title?: string; labels?: Array<{ name?: string } | string> }): boolean {
    const labels = extractLabelNames(issue.labels);
    return labels.includes("type:conversation") && labels.includes(`session:${session.sessionId}`);
  }

  private resetIssueBinding(session: SessionMirrorState): void {
    session.issueNumber = undefined;
    session.issueTitle = undefined;
    session.titleSource = undefined;
    session.lastSummaryHash = undefined;
    session.lastMirroredCount = 0;
    session.turnCount = 0;
    session.finalizedAt = undefined;
  }
}

async function fexists(p: string): Promise<boolean> { try { return (await fs.promises.stat(p)).isFile(); } catch { return false; } }
function isNotFoundError(error: unknown): boolean {
  const text = String(error);
  return text.includes("HTTP 404");
}
/** Derive an initial placeholder title for a new conversation. The real title is generated by LLM once enough messages are available. */
export function deriveInitialTitle(_messages: NormalizedMessage[], sessionId: string): string {
  return `${SESSION_TITLE_PREFIX}${sessionId}`;
}

function parseSummaryAndTitle(raw: string): { summary: string; title?: string } {
  const tryParse = (s: string): { summary: string; title?: string } | null => {
    try {
      const p = JSON.parse(s) as { summary?: unknown; title?: unknown };
      const summary = typeof p?.summary === "string" && p.summary.trim() ? p.summary.trim() : null;
      if (!summary) return null;
      const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
      return { summary, title };
    } catch {
      const i = s.indexOf("{"), j = s.lastIndexOf("}");
      if (i >= 0 && j > i) {
        try {
          const p = JSON.parse(s.slice(i, j + 1)) as { summary?: unknown; title?: unknown };
          const summary = typeof p?.summary === "string" && p.summary.trim() ? p.summary.trim() : null;
          if (!summary) return null;
          const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
          return { summary, title };
        } catch { return null; }
      }
      return null;
    }
  };
  const t = raw.trim();
  const direct = tryParse(t); if (direct) return direct;
  const f = /^```(?:json)?\s*([\s\S]*?)```$/i.exec(t);
  if (f?.[1]) { const nested = tryParse(f[1].trim()); if (nested) return nested; }
  return { summary: t };
}

function parseFinalArtifacts(raw: string): { summary: string; title?: string; candidates: MemoryCandidate[] } {
  const parsedSummary = parseSummaryAndTitle(raw);
  const candidates = parseCandidates(raw);
  return {
    summary: parsedSummary.summary,
    ...(parsedSummary.title ? { title: parsedSummary.title } : {}),
    candidates,
  };
}
