// Session mirroring: creates/updates GitHub issues and comments for each conversation.
import fs from "node:fs";
import path from "node:path";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/core";
import { AGENT_LABEL_PREFIX, DEFAULT_LABELS, SESSION_TITLE_PREFIX, extractLabelNames } from "./config.js";
import type { GitHubIssueClient } from "./github-client.js";
import { normalizeMessages, readTranscriptSnapshot } from "./transcript.js";
import type { ClawMemPluginConfig, NormalizedMessage, SessionMirrorState, TranscriptSnapshot } from "./types.js";
import { fmtTranscript, fmtTranscriptFrom, localDate, localDateTime, sha256, sliceTranscriptDelta, subKey } from "./utils.js";
import { parseFlatYaml, stringifyFlatYaml } from "./yaml.js";

export class ConversationMirror {
  constructor(private readonly client: GitHubIssueClient, private readonly api: OpenClawPluginApi, private readonly config: ClawMemPluginConfig) {}

  shouldMirror(sessionId: string, messages: NormalizedMessage[]): boolean {
    if (sessionId.startsWith("slug-generator-")) return false;
    const first = messages.find((m) => m.role === "user")?.text ?? "";
    if (first.includes("generate a short 1-2 word filename slug") && first.includes("Reply with ONLY the slug")) return false;
    if (first.includes("Summarize the following conversation.") && first.includes('Return valid JSON only in the form {"summary":"..."}')) return false;
    if (first.includes("Extract durable memories from the conversation below.") && first.includes('Return JSON only in the form {"save":')) return false;
    if (first.includes("Maintain a rolling digest of the conversation below.") && first.includes('Return valid JSON only in the form {"digest":"...","title":"..."}')) return false;
    if (first.includes("Write the final issue summary for the conversation below.") && first.includes('Return valid JSON only in the form {"summary":"...","title":"..."}')) return false;
    if (first.includes("Extract atomic durable memory candidates from the conversation delta below.")) return false;
    if (first.includes("Reconcile extracted durable memory candidates against existing memories.")) return false;
    return true;
  }

  async loadSnapshot(session: SessionMirrorState, fallback: unknown[]): Promise<TranscriptSnapshot> {
    const filePath = await this.resolveTranscriptPath(session.sessionFile);
    if (filePath) {
      session.sessionFile = filePath;
      try {
        const t = await readTranscriptSnapshot(filePath);
        return { sessionId: t.sessionId ?? session.sessionId, messages: t.messages };
      } catch (error) {
        this.api.logger.warn(`clawmem: transcript read failed for ${filePath}: ${String(error)}`);
      }
    }
    return { sessionId: session.sessionId, messages: normalizeMessages(fallback) };
  }

  async ensureIssue(session: SessionMirrorState, snapshot: TranscriptSnapshot): Promise<void> {
    if (session.issueNumber) {
      const existing = await this.lookupBoundIssue(session);
      if (existing && this.isBoundIssue(session, existing)) {
        session.issueTitle = existing.title?.trim() || session.issueTitle;
        return;
      }
      this.api.logger.warn(
        `clawmem: issue binding for ${session.sessionId} is stale or mismatched (${session.issueNumber}); recreating`,
      );
      this.resetIssueBinding(session);
    }
    // Use placeholder title; real title is generated by LLM once enough messages are available.
    const title = deriveInitialTitle(snapshot.messages, session.sessionId);
    const labels = this.buildLabels(session, snapshot, false);
    const body = this.renderBody(session, snapshot, "pending", false);
    await this.client.ensureLabels(labels);
    const issue = await this.client.createIssue({ title, body, labels });
    session.issueNumber = issue.number;
    session.issueTitle = issue.title ?? title;
    session.titleSource = "placeholder";
    session.lastSummaryHash = sha256(`${title}\n${body}\nopen`);
    session.createdAt = new Date().toISOString();
    session.updatedAt = session.createdAt;
  }

  async syncBody(session: SessionMirrorState, snapshot: TranscriptSnapshot, summary: string, closed: boolean, titleOverride?: string): Promise<void> {
    if (!session.issueNumber) return;
    // Prefer explicit override (LLM-generated title), then keep existing title, then fall back to session ID.
    const title = titleOverride?.trim() || session.issueTitle || `${SESSION_TITLE_PREFIX}${session.sessionId}`;
    const body = this.renderBody(session, snapshot, summary, closed);
    const hash = sha256(`${title}\n${body}\n${closed ? "closed" : "open"}`);
    if (hash === session.lastSummaryHash) return;
    await this.client.updateIssue(session.issueNumber, { title, body, ...(closed ? { state: "closed" as const } : {}) });
    session.issueTitle = title;
    if (titleOverride?.trim()) session.titleSource = "llm";
    session.lastSummaryHash = hash;
  }

  async syncLabels(session: SessionMirrorState, snapshot: TranscriptSnapshot, closed: boolean): Promise<void> {
    if (!session.issueNumber) return;
    const labels = this.buildLabels(session, snapshot, closed);
    await this.client.ensureLabels(labels);
    await this.client.syncManagedLabels(session.issueNumber, labels);
  }

  async appendComments(issueNumber: number, messages: NormalizedMessage[]): Promise<number> {
    let count = 0;
    for (const msg of messages) {
      try { await this.client.createComment(issueNumber, `role: ${msg.role}\n\n${msg.text.trim()}`); count++; }
      catch (error) { this.api.logger.warn(`clawmem: conversation comment failed: ${String(error)}`); break; }
    }
    return count;
  }

  async generateRollingDigest(
    session: SessionMirrorState,
    snapshot: TranscriptSnapshot,
    fromCursor: number,
    previousDigest?: string,
  ): Promise<{ digest: string; title?: string }> {
    const { anchorStart, deltaStart, anchorMessages, deltaMessages } = sliceTranscriptDelta(snapshot.messages, fromCursor, 2);
    if (deltaMessages.length === 0) {
      return { digest: previousDigest?.trim() || "" };
    }
    const subagent = this.api.runtime.subagent;
    const sessionKey = subKey(session, "digest");
    const message = [
      "Maintain a rolling digest of the conversation below.",
      'Return valid JSON only in the form {"digest":"...","title":"..."}',
      "Update the digest so it accurately represents the conversation so far in 4-8 concise factual sentences.",
      "Focus on decisions, constraints, preferences, open workstreams, and concrete outcomes worth carrying forward.",
      "Use the anchor messages only for context resolution. The new messages are the only part that must be incorporated now.",
      "Title is optional. If provided, keep it under 50 characters and accurately describe the overall conversation.",
      "",
      "<previous-digest>",
      previousDigest?.trim() || "None.",
      "</previous-digest>",
      "",
      "<anchor-messages>",
      anchorMessages.length > 0 ? fmtTranscriptFrom(anchorMessages, anchorStart) : "None.",
      "</anchor-messages>",
      "",
      "<new-messages>",
      fmtTranscriptFrom(deltaMessages, deltaStart),
      "</new-messages>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey,
        message,
        deliver: false,
        lane: "clawmem-digest",
        idempotencyKey: sha256(`${session.sessionId}:${fromCursor}:${snapshot.messages.length}:digest-v1`),
        extraSystemPrompt: "You maintain rolling conversation digests for ClawMem. Output JSON only with string fields digest and optional title.",
      });
      const wait = await subagent.waitForRun({ runId: run.runId, timeoutMs: this.config.digestWaitTimeoutMs });
      if (wait.status === "timeout") throw new Error("digest subagent timed out");
      if (wait.status === "error") throw new Error(wait.error || "digest subagent failed");
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 50 })).messages);
      const text = [...msgs].reverse().find((e) => e.role === "assistant" && e.text.trim())?.text;
      if (!text) throw new Error("digest subagent returned no assistant text");
      return parseDigestAndTitle(text);
    } finally {
      subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {});
    }
  }

  async generateFinalSummaryFromDigest(
    session: SessionMirrorState,
    snapshot: TranscriptSnapshot,
    digestText: string,
  ): Promise<{ summary: string; title?: string }> {
    if (!digestText.trim() && snapshot.messages.length === 0) throw new Error("no conversation content to summarize");
    const tailStart = Math.max(0, snapshot.messages.length - 6);
    const tailMessages = snapshot.messages.slice(tailStart);
    const subagent = this.api.runtime.subagent;
    const sessionKey = subKey(session, "summary-final");
    const message = [
      "Write the final issue summary for the conversation below.",
      'Return valid JSON only in the form {"summary":"...","title":"..."}',
      "The summary should be concise, factual, and written in 2-4 sentences.",
      "Use the rolling digest as the primary source of truth, and use the recent tail only to preserve freshness and wording accuracy.",
      "Do not include markdown, bullet points, or analysis.",
      "",
      "Title rules:",
      "- Under 50 characters, accurately describe the main topic or task.",
      "- Should let someone immediately know what the conversation is about.",
      "- Must be in the same language as the majority of the conversation content.",
      "- Good: precise, descriptive, specific. Bad: vague, overly creative, generic.",
      "",
      "<rolling-digest>",
      digestText.trim() || "None.",
      "</rolling-digest>",
      "",
      "<recent-tail>",
      tailMessages.length > 0 ? fmtTranscriptFrom(tailMessages, tailStart) : "None.",
      "</recent-tail>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey,
        message,
        deliver: false,
        lane: "clawmem-summary",
        idempotencyKey: sha256(`${session.sessionId}:${snapshot.messages.length}:summary-final-v1`),
        extraSystemPrompt: "You write final conversation issue summaries for ClawMem. Output JSON only with string fields summary and title.",
      });
      const wait = await subagent.waitForRun({ runId: run.runId, timeoutMs: this.config.summaryWaitTimeoutMs });
      if (wait.status === "timeout") throw new Error("summary subagent timed out");
      if (wait.status === "error") throw new Error(wait.error || "summary subagent failed");
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 50 })).messages);
      const text = [...msgs].reverse().find((e) => e.role === "assistant" && e.text.trim())?.text;
      if (!text) throw new Error("summary subagent returned no assistant text");
      return parseSummaryAndTitle(text);
    } finally {
      subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {});
    }
  }

  async generateSummaryAndTitle(session: SessionMirrorState, snapshot: TranscriptSnapshot): Promise<{ summary: string; title?: string }> {
    if (snapshot.messages.length === 0) throw new Error("no conversation messages to summarize");
    const subagent = this.api.runtime.subagent;
    const sessionKey = subKey(session, "summary");
    const message = [
      "Summarize the following conversation and generate a short title.",
      'Return valid JSON only in the form {"summary":"...","title":"..."}',
      "The summary should be concise, factual, and written in 2-4 sentences.",
      "Do not include markdown, bullet points, or analysis.",
      "",
      "Title rules:",
      "- Under 50 characters, accurately describe the main topic or task.",
      "- Should let someone immediately know what the conversation is about.",
      "- Must be in the same language as the majority of the conversation content.",
      "- Good: precise, descriptive, specific. Bad: vague, overly creative, generic.",
      "", "<conversation>", fmtTranscript(snapshot.messages), "</conversation>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey, message, deliver: false, lane: "clawmem-summary",
        idempotencyKey: sha256(`${session.sessionId}:${snapshot.messages.length}:summary-v2`),
        extraSystemPrompt: "You summarize conversations and generate accurate, descriptive titles. Output JSON only with string fields summary and title.",
      });
      const wait = await subagent.waitForRun({ runId: run.runId, timeoutMs: this.config.summaryWaitTimeoutMs });
      if (wait.status === "timeout") throw new Error("summary subagent timed out");
      if (wait.status === "error") throw new Error(wait.error || "summary subagent failed");
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 50 })).messages);
      const text = [...msgs].reverse().find((e) => e.role === "assistant" && e.text.trim())?.text;
      if (!text) throw new Error("summary subagent returned no assistant text");
      return parseSummaryAndTitle(text);
    } finally { subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {}); }
  }

  /** If the title has not yet been generated by LLM, generate an accurate title from the full conversation and update the issue. */
  async syncTitle(session: SessionMirrorState, snapshot: TranscriptSnapshot): Promise<void> {
    if (!session.issueNumber) return;
    if (session.titleSource === "llm") return;
    if (snapshot.messages.length < 2) return;
    try {
      const title = await this.generateTitle(session, snapshot);
      if (title) {
        await this.client.updateIssue(session.issueNumber, { title });
        session.issueTitle = title;
        session.titleSource = "llm";
      }
    } catch (e) {
      this.api.logger.warn(`clawmem: title sync failed: ${String(e)}`);
    }
  }

  /** Generate an accurate, descriptive title from the full conversation content via LLM. */
  async generateTitle(session: SessionMirrorState, snapshot: TranscriptSnapshot): Promise<string | undefined> {
    if (snapshot.messages.length === 0) return undefined;
    const subagent = this.api.runtime.subagent;
    const sessionKey = subKey(session, "title");
    const message = [
      "Generate a short, accurate title for the following conversation.",
      'Return valid JSON only in the form {"title":"..."}',
      "",
      "Title rules:",
      "- Under 50 characters.",
      "- Accurately describe the main topic or task of the conversation.",
      "- Should let someone immediately know what the conversation is about.",
      "- Must be in the same language as the majority of the conversation content.",
      "- Good: precise, descriptive, specific. Bad: vague, overly creative, generic.",
      "",
      "<conversation>",
      fmtTranscript(snapshot.messages),
      "</conversation>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey, message, deliver: false, lane: "clawmem-title",
        idempotencyKey: sha256(`${session.sessionId}:${snapshot.messages.length}:title-v1`),
        extraSystemPrompt: "You generate accurate, descriptive titles for conversations. Output JSON only with a string field title.",
      });
      const wait = await subagent.waitForRun({ runId: run.runId, timeoutMs: 30000 });
      if (wait.status === "timeout" || wait.status === "error") return undefined;
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 10 })).messages);
      const text = [...msgs].reverse().find((e) => e.role === "assistant" && e.text.trim())?.text;
      if (!text) return undefined;
      return parseTitle(text);
    } catch (e) {
      this.api.logger.warn(`clawmem: title generation failed: ${String(e)}`);
      return undefined;
    } finally {
      subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {});
    }
  }

  /** Re-title all existing conversation issues. Uses summary when available, falls back to reading comments. */
  async retitleConversations(): Promise<{ updated: number; skipped: number; failed: number; retitledIssues: number[] }> {
    let updated = 0, skipped = 0, failed = 0;
    const retitledIssues: number[] = [];
    let page = 1;
    while (true) {
      const issues = await this.client.listIssues({ labels: ["type:conversation"], state: "all", page, perPage: 50 });
      if (issues.length === 0) break;
      for (const issue of issues) {
        try {
          const yaml = parseFlatYaml(issue.body || "");
          const summary = yaml.summary;
          let titleInput: string | undefined;
          if (summary && summary !== "pending" && !summary.startsWith("failed:")) {
            titleInput = summary;
          } else {
            // No usable summary — reconstruct conversation from issue comments.
            const comments = await this.client.listComments(issue.number, { perPage: 50 });
            const conversationText = comments
              .map((c) => c.body?.trim())
              .filter((b): b is string => Boolean(b))
              .join("\n\n");
            if (conversationText.length >= 20) {
              // Cap to avoid excessive token usage in LLM call.
              titleInput = conversationText.length > 4000 ? conversationText.slice(0, 4000) + "\n..." : conversationText;
            }
          }
          if (!titleInput) { skipped++; continue; }
          const title = await this.generateTitleFromText(titleInput, `retitle-${issue.number}`);
          if (!title) { skipped++; continue; }
          await this.client.updateIssue(issue.number, { title });
          this.api.logger.info?.(`clawmem: retitled issue #${issue.number} -> "${title}"`);
          retitledIssues.push(issue.number);
          updated++;
        } catch (e) {
          this.api.logger.warn(`clawmem: retitle failed for issue #${issue.number}: ${String(e)}`);
          failed++;
        }
      }
      if (issues.length < 50) break;
      page++;
    }
    return { updated, skipped, failed, retitledIssues };
  }

  private async generateTitleFromText(text: string, uniqueKey: string): Promise<string | undefined> {
    const subagent = this.api.runtime.subagent;
    const sessionKey = `clawmem-${uniqueKey}`;
    const message = [
      "Generate a short, accurate title based on the following conversation content.",
      'Return valid JSON only in the form {"title":"..."}',
      "",
      "Title rules:",
      "- Under 50 characters.",
      "- Accurately describe the main topic or task.",
      "- Should let someone immediately know what the conversation was about.",
      "- Must be in the same language as the content.",
      "- Good: precise, descriptive, specific. Bad: vague, overly creative, generic.",
      "",
      "<content>",
      text,
      "</content>",
    ].join("\n");
    try {
      const run = await subagent.run({
        sessionKey, message, deliver: false, lane: "clawmem-retitle",
        idempotencyKey: sha256(`retitle:${uniqueKey}:${text.slice(0, 200)}`),
        extraSystemPrompt: "You generate accurate, descriptive titles. Output JSON only with a string field title.",
      });
      const wait = await subagent.waitForRun({ runId: run.runId, timeoutMs: 30000 });
      if (wait.status === "timeout" || wait.status === "error") return undefined;
      const msgs = normalizeMessages((await subagent.getSessionMessages({ sessionKey, limit: 10 })).messages);
      const raw = [...msgs].reverse().find((e) => e.role === "assistant" && e.text.trim())?.text;
      if (!raw) return undefined;
      return parseTitle(raw);
    } catch (e) {
      this.api.logger.warn(`clawmem: title generation from text failed (${uniqueKey}): ${String(e)}`);
      return undefined;
    } finally {
      subagent.deleteSession({ sessionKey, deleteTranscript: true }).catch(() => {});
    }
  }

  private buildLabels(session: SessionMirrorState, _snapshot: TranscriptSnapshot, _closed: boolean): string[] {
    const labels = new Set([...DEFAULT_LABELS, "type:conversation", `session:${session.sessionId}`]);
    if (session.agentId) labels.add(`${AGENT_LABEL_PREFIX}${session.agentId}`);
    return [...labels].filter((l) => l.trim().length > 0);
  }

  private renderBody(session: SessionMirrorState, snapshot: TranscriptSnapshot, summary: string, _closed: boolean): string {
    const dates = this.resolveDates(session, snapshot.messages);
    return stringifyFlatYaml([
      ["type", "conversation"], ["session_id", session.sessionId], ["date", dates.date],
      ["start_at", dates.startAt], ["end_at", dates.endAt],
      ["summary", summary],
    ]);
  }

  private resolveDates(session: SessionMirrorState, messages: NormalizedMessage[]): { date: string; startAt: string; endAt: string } {
    const ts = messages.map((m) => m.timestamp).filter((v): v is string => Boolean(v?.trim()))
      .map((v) => new Date(v)).filter((d) => Number.isFinite(d.getTime()));
    const fallbackStart = session.createdAt ? new Date(session.createdAt) : new Date();
    const fallbackEnd = session.updatedAt ? new Date(session.updatedAt) : fallbackStart;
    const start = ts[0] ?? fallbackStart, end = ts.at(-1) ?? fallbackEnd;
    return { date: localDate(start), startAt: localDateTime(start), endAt: localDateTime(end) };
  }

  private async resolveTranscriptPath(filePath: string | undefined): Promise<string | null> {
    if (!filePath) return null;
    if (await fexists(filePath)) return filePath;
    try {
      const dir = path.dirname(filePath), prefix = `${path.basename(filePath)}.reset.`;
      const latest = (await fs.promises.readdir(dir, { withFileTypes: true }))
        .filter((e) => e.isFile() && e.name.startsWith(prefix)).map((e) => e.name).sort().at(-1);
      if (latest) {
        this.api.logger.info?.(`clawmem: using reset transcript ${path.join(dir, latest)} because ${filePath} is missing`);
        return path.join(dir, latest);
      }
    } catch { /* directory unreadable */ }
    return null;
  }

  private async lookupBoundIssue(session: SessionMirrorState): Promise<{ number: number; title?: string; labels?: Array<{ name?: string } | string> } | null> {
    if (!session.issueNumber) return null;
    try {
      return await this.client.getIssue(session.issueNumber);
    } catch (error) {
      if (isNotFoundError(error)) return null;
      throw error;
    }
  }

  private isBoundIssue(session: SessionMirrorState, issue: { title?: string; labels?: Array<{ name?: string } | string> }): boolean {
    const labels = extractLabelNames(issue.labels);
    return labels.includes("type:conversation") && labels.includes(`session:${session.sessionId}`);
  }

  private resetIssueBinding(session: SessionMirrorState): void {
    session.issueNumber = undefined;
    session.issueTitle = undefined;
    session.titleSource = undefined;
    session.lastSummaryHash = undefined;
    session.lastMirroredCount = 0;
    session.turnCount = 0;
    session.finalizedAt = undefined;
  }
}

async function fexists(p: string): Promise<boolean> { try { return (await fs.promises.stat(p)).isFile(); } catch { return false; } }
function isNotFoundError(error: unknown): boolean {
  const text = String(error);
  return text.includes("HTTP 404");
}
/** Derive an initial placeholder title for a new conversation. The real title is generated by LLM once enough messages are available. */
export function deriveInitialTitle(_messages: NormalizedMessage[], sessionId: string): string {
  return `${SESSION_TITLE_PREFIX}${sessionId}`;
}

function parseSummaryAndTitle(raw: string): { summary: string; title?: string } {
  const tryParse = (s: string): { summary: string; title?: string } | null => {
    try {
      const p = JSON.parse(s) as { summary?: unknown; title?: unknown };
      const summary = typeof p?.summary === "string" && p.summary.trim() ? p.summary.trim() : null;
      if (!summary) return null;
      const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
      return { summary, title };
    } catch {
      const i = s.indexOf("{"), j = s.lastIndexOf("}");
      if (i >= 0 && j > i) {
        try {
          const p = JSON.parse(s.slice(i, j + 1)) as { summary?: unknown; title?: unknown };
          const summary = typeof p?.summary === "string" && p.summary.trim() ? p.summary.trim() : null;
          if (!summary) return null;
          const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
          return { summary, title };
        } catch { return null; }
      }
      return null;
    }
  };
  const t = raw.trim();
  const direct = tryParse(t); if (direct) return direct;
  const f = /^```(?:json)?\s*([\s\S]*?)```$/i.exec(t);
  if (f?.[1]) { const nested = tryParse(f[1].trim()); if (nested) return nested; }
  return { summary: t };
}

function parseDigestAndTitle(raw: string): { digest: string; title?: string } {
  const tryParse = (s: string): { digest: string; title?: string } | null => {
    try {
      const p = JSON.parse(s) as { digest?: unknown; title?: unknown };
      const digest = typeof p?.digest === "string" && p.digest.trim() ? p.digest.trim() : null;
      if (!digest) return null;
      const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
      return { digest, title };
    } catch {
      const i = s.indexOf("{"), j = s.lastIndexOf("}");
      if (i >= 0 && j > i) {
        try {
          const p = JSON.parse(s.slice(i, j + 1)) as { digest?: unknown; title?: unknown };
          const digest = typeof p?.digest === "string" && p.digest.trim() ? p.digest.trim() : null;
          if (!digest) return null;
          const title = typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
          return { digest, title };
        } catch { return null; }
      }
      return null;
    }
  };
  const t = raw.trim();
  const direct = tryParse(t);
  if (direct) return direct;
  const f = /^```(?:json)?\s*([\s\S]*?)```$/i.exec(t);
  if (f?.[1]) {
    const nested = tryParse(f[1].trim());
    if (nested) return nested;
  }
  return { digest: t };
}

function parseTitle(raw: string): string | undefined {
  const tryParse = (s: string): string | undefined => {
    try {
      const p = JSON.parse(s) as { title?: unknown };
      return typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
    } catch {
      const i = s.indexOf("{"), j = s.lastIndexOf("}");
      if (i >= 0 && j > i) {
        try {
          const p = JSON.parse(s.slice(i, j + 1)) as { title?: unknown };
          return typeof p?.title === "string" && p.title.trim() ? p.title.trim() : undefined;
        } catch { return undefined; }
      }
      return undefined;
    }
  };
  const t = raw.trim();
  const direct = tryParse(t);
  if (direct) return direct;
  const f = /^```(?:json)?\s*([\s\S]*?)```$/i.exec(t);
  if (f?.[1]) return tryParse(f[1].trim());
  return undefined;
}
